name: MyTrainingWorkflow
on: 
  push:
    branches: 
      - main 
  workflow_dispatch: 
jobs:
  FirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Well, Hello GitHub Actions WORLD"
            
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: List files in REPO
        run: |
          echo "The repository ActionsInAction2 contains following FILES:"
          tree
