#
# author: Jeff Callas
#
name: MyTrainingWorkflow
on: 
  push:
    branches: 
      - main 
  workflow_dispatch: 
jobs:
  FirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Well, Hello GitHub Actions WORLD"
            
      - name: STEP-1 Checkout
        uses: actions/checkout@v4.1.7

      - name: STEP-2 List files in REPO
        run: |
          echo "The repository ActionsInAction2 contains following FILES:"
          tree

      - name: STEP-3 FINAL STEP
        run: |
          echo "Execution of FINAL STEP"
